# Generated by Django 5.2.12 on 2026-06-01 00:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0351_create_ocp_cost_breakdown_p"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocpgpuusagelineitem",
            name="gpu_pod_utilization",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ocpgpuusagelineitemdaily",
            name="gpu_pod_utilization",
            field=models.FloatField(null=True),
        ),
    ]
